### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by eioo** [excogitatr/ant_icons#1]
My first time using this library and I'm experiencing problem where the icons are not showing up. Example:

![image](https://i.imgur.com/C9biIbE.png)

I'm using Android API 25 (Pixel 2) and Dart SDK version 2.7.0. This is the project I tried to use it with: https://github.com/rareagency/event-app-showcase/tree/master/app

Here is my `pubspec.yaml`:

```
name: eventapp
description: Event app demo
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+4
  intl: ^0.16.1
  collection: ^1.14.11
  ant_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
          weight: 700

  uses-material-design: true

  assets:
   - assets/

```
